# Generated by Django 4.2.1 on 2023-09-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cat', models.CharField(max_length=50)),
                ('descreption', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
