# Generated by Django 4.2.1 on 2023-09-12 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency_app', '0002_offre'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='agency_app.category'),
            preserve_default=False,
        ),
    ]
