# Generated by Django 4.2.1 on 2023-09-12 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency_app', '0003_offre_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('nm_tlphn', models.CharField(max_length=50)),
                ('place_reservé', models.IntegerField()),
                ('Offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_app.offre')),
            ],
        ),
    ]
